In [1]:
from BlackJackBattleEnv import *
from DDQN import *
import random
import torch
import numpy as np

d:\Miniconda\miniconda\envs\start\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = DDQN(3, 2)
# model.cuda()
trainer = Trainer(BlackJack(dealer_policy=SimplePolicy(17)), model, buffer_capacity=200)
trainer.train()

 content:[200/200]epoch: [0/20]
 step:[0/1000], loss:15.021397590637207

IndexError: list assignment index out of range

In [ ]:
torch.Tensor([2,3]).cuda()

In [ ]:
for i in range(10):
    print(i%3)

0
1
2
0
1
2
0
1
2
0


In [ ]:
model = nn.Sequential(
    nn.Linear(2,3),
    nn.Linear(3,3),
    nn.Linear(3,1)
)
for par in model.parameters():
    # par.data.clone()[0]=100
    print(par.data)

tensor([[ 0.5301, -0.0123],
        [ 0.4605,  0.1562],
        [-0.6228, -0.5274]])
tensor([-0.6899, -0.4012,  0.3382])
tensor([[-0.4561,  0.0961,  0.1113],
        [ 0.1206, -0.4139, -0.3063],
        [ 0.2947,  0.4743, -0.1159]])
tensor([-0.5336, -0.2841,  0.4474])
tensor([[ 0.4543, -0.1230, -0.4593]])
tensor([-0.1155])


In [ ]:
env = BlackJack(dealer_policy=SimplePolicy(17))
env.reset()
env.step(1)
# env.dealer_policy = 

((18, 8, False), 0, False, {})

In [ ]:
A = torch.Tensor([1,2])
B = torch.Tensor([2,3])
((A-B) * (A-B)).sum()

tensor(2.)

In [ ]:
A = [1,2,3,4,5,6]

idx = [random.randint(0,len(A)-1) for _ in range(3)]
[A[i] for i in idx]

[6, 6, 4]

In [ ]:
idx = torch.randn((32,10)).max(dim=1)
idx[0].size()

torch.Size([32])

In [ ]:
env = BlackJack(dealer_policy=SimplePolicy(17))
print('='*120)
print('玩家阶段')
obs = env.reset()
info = f'玩家手牌{obs[0]:3}, 庄家明牌 {obs[1]:3}，是否有可用Ace：{obs[2]:2}:玩家决策：'
x = int(input(info))
while x in {0, 1}:
    obs, reward, done, _ = env.step(x)

    if done:
        if reward == 1:
            print('玩家胜利')
        elif reward == 0:
            print('平局')
        else:
            print('庄家胜利')
        print('='*120)
        obs = env.reset()
        print('玩家阶段')

    info = f'玩家手牌{obs[0]:3}, 庄家明牌 {obs[1]:3}，是否有可用Ace：{obs[2]:2}:玩家决策：'
    x = int(input(info))

玩家阶段


ValueError: invalid literal for int() with base 10: ''